# name: Dev Deployment

# on:
#   workflow_run:
#     workflows: ["Build and Push"]
#     types:
#       - completed

# jobs:
#   deploy_to_dev:
#     if: github.event.repository.fork == false
#     runs-on: self-hosted

#     steps:
#       - name: Deploy to dev environment
#         uses: appleboy/ssh-action@v1.0.3
#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           password: ${{ secrets.PASSWORD }}
#           script: |
#             cd bingofe/dev/bingo_fe
#             ./scripts/dev_deploy.sh 
