name: Dev Deployment

on:
  push:
    branches:
      - dev

jobs:
  cleanup:
    runs-on: self-hosted
    steps:
      - name: Delete Old Artifacts
        uses: actions/github-script@v6
        with:
          script: |
            const res = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })

            res.data.artifacts.forEach(async ({ id }) => {
              await github.rest.actions.deleteArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: id,
              })
            })

  build:
    needs: cleanup
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t hngtechie/bingofe:dev -f docker/development/Dockerfile .

      - name: Save and compress Docker image
        run: |
          docker save hngtechie/bingofe:dev > bingofe-dev.tar
          gzip bingofe-dev.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: bingofe-dev.tar.gz
          retention-days: 1

  deploy-to-dev:
    needs: build
    runs-on: self-hosted
    if: github.event.repository.fork == false
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: docker-image
          path: .

      - name: Copy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "bingofe-dev.tar.gz"
          target: "/tmp/bingofe"

      - name: Deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /tmp/bingofe
            gunzip bingofe-dev.tar.gz
            docker load < bingofe-dev.tar
            rm -f bingofe-dev.tar
            cd /home/${{ secrets.USERNAME }}/bingofe/dev/bingo_fe
            chmod +x ./scripts/*.sh
            ./scripts/dev_deploy.sh
