
name: PR Deploy
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  deploy-pr:
    environment: 
      name: preview
      url: ${{ steps.deploy.outputs.preview-url }}
    runs-on: self-hosted
    steps:
      - name: Checkout to branch
        uses: actions/checkout@v4
      - id: deploy
        name: Pull Request Deploy
        uses: hngprojects/pr-deploy@feat_auth_private_repo
        with:
          server_host: ${{ secrets.HOST }}
          server_username: ${{ secrets.USERNAME }}
          server_password: ${{ secrets.PASSWORD }}
          comment: true
          context: '.'
          dockerfile: 'docker/development/Dockerfile'
          exposed_port: '3000'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print Preview Url
        run: |
          echo "Preview Url: ${{ steps.deploy.outputs.preview-url }}" 
