name: Production Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/**

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t hngtechie/bingofe:prod -f docker/prod/Dockerfile .

      - name: Save and compress Docker image
        run: |
          docker save hngtechie/bingofe:prod > bingofe-prod.tar
          gzip bingofe-prod.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: bingofe-prod.tar.gz

  deploy-to-production:
    needs: build
    runs-on: self-hosted
    if: github.event.repository.fork == false
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: docker-image
          path: .

      - name: Copy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "bingofe-prod.tar.gz"
          target: "/tmp/bingofe"

      - name: Deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /tmp/bingofe
            gunzip bingofe-prod.tar.gz
            docker load < bingofe-prod.tar
            rm -f bingofe-prod.tar
            cd /home/${{ secrets.USERNAME }}/bingofe/prod/bingo_fe
            chmod +x ./scripts/*.sh
            ./scripts/production_staging.sh
