name: Remove old artifacts

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  remove-old-artifacts:
    runs-on: self-hosted
    timeout-minutes: 10

    steps:
    - name: Remove artifacts older than 1 day
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '1 day' # Removes artifacts older than 1 day
