name: Remove old artifacts

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  remove-old-artifacts:
    runs-on: self-hosted
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Delete artifact older than 1 day
      uses: geekyeggo/delete-artifact@v5
      with:
        name: my-artifact # Replace with your actual artifact name
        days-old: 1       # Specify the minimum age of artifacts to delete (in days)
