name: Remove old artifacts

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install gh

    - name: Authenticate GitHub CLI
      run: |
        gh auth login --with-token < ${{ secrets.GITHUB_TOKEN }}

    - name: List and delete artifacts
      run: |
        # List all artifact names
        artifacts=$(gh run list --json artifacts --jq '.[].artifacts[].name')

        # Loop through each artifact name and delete it
        for artifact in $artifacts; do
          gh artifact delete "$artifact" --confirm
        done
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
