name: Remove old artifacts

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: List and delete artifacts
      run: |
        artifacts=$(gh run artifacts --json name --jq '.[].name')
        for artifact in $artifacts; do
          gh run delete-artifact $artifact --confirm
        done
