name: Staging Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - staging
    paths-ignore:
      - .github/workflows/**

jobs:
  deploy_to_staging:
    runs-on: bingo-server

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Staging Server
        uses: garygrossgarten/github-action-ssh@v0.7.2
        with:
          host: ${{ secrets.HOST }}
          port: 22
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          command: |
            export NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            export GIF_API_KEY=${{ secrets.GIF_API_KEY }}
            cd /home/bingofe/remote-bingo/staging/bingo_fe
            git pull origin staging
            chmod +x ./scripts/staging_deploy.sh
            ./scripts/staging_deploy.sh
