name: Staging Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - staging
    paths-ignore:
      - .github/workflows/**

jobs:
  build_and_deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          corepack enable pnpm
          pnpm install --frozen-lockfile

      - name: Build Application
        run: pnpm run build

      - name: Deploy to Staging Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            export NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            export GIF_API_KEY=${{ secrets.GIF_API_KEY }}
            cd /home/starlight-nestjs/remote-bingo/staging/bingo_fe
            git pull origin staging
            chmod +x ./scripts/staging_deploy.sh
            ./scripts/staging_deploy.sh
