name: Staging Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - staging
    paths-ignore:
      - .github/workflows/**

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t hngtechie/bingofe:staging -f docker/development/Dockerfile .

      - name: Save and compress Docker image
        run: |
          docker save hngtechie/bingofe:staging > bingofe-staging.tar
          gzip bingofe-staging.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: bingofe-staging.tar.gz

  deploy-to-staging:
    needs: build
    runs-on: self-hosted
    if: github.event.repository.fork == false
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: docker-image
          path: .

      - name: Copy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "bingofe-staging.tar.gz"
          target: "/tmp/bingofe"

      - name: Deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /tmp/bingofe
            gunzip bingofe-staging.tar.gz
            docker load < bingofe-staging.tar
            rm -f bingofe-staging.tar
            cd /home/${{ secrets.USERNAME }}/bingofe/staging/bingo_fe
            chmod +x ./scripts/*.sh
            ./scripts/staging_deploy.sh
