name: Staging Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - staging

jobs:
  deploy-staging:
    runs-on: bingo-server
    steps:
      - name: Deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            export NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            export GIF_API_KEY=${{ secrets.GIF_API_KEY }}
            cd /home/bingofe/remote-bingo/staging/bingo_fe
            git pull origin staging
            chmod +x ./scripts/staging_deploy.sh
            ./scripts/staging_deploy.sh
