name: Staging Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - staging
    paths-ignore:
      - .github/workflows/**

jobs:
  build_and_push:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: docker/staging/Dockerfile
          push: true
          tags: hngtechie/bingofe:staging

  deploy_to_staging:
    needs: build_and_push
    if: github.event.repository.fork == false
    runs-on: self-hosted

    steps:
      - name: Deploy to staging environment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd bingofe/staging/bingo_fe
            chmod +x ./scripts/staging_deploy.sh
            ./scripts/staging_deploy.sh

# name: Staging Deployment

# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - staging
#     paths-ignore:
#       - .github/workflows/**

# jobs:
#   build:
#     runs-on: self-hosted
#     steps:
#       - uses: actions/checkout@v2

#       - name: Build Docker image
#         run: docker build -t hngtechie/bingofe:staging -f docker/staging/Dockerfile .

#       - name: Save and compress Docker image
#         run: |
#           docker save hngtechie/bingofe:staging > bingofe-staging.tar
#           gzip bingofe-staging.tar

#       - name: Upload artifact
#         uses: actions/upload-artifact@v2
#         with:
#           name: docker-image
#           path: bingofe-staging.tar.gz
#           retention-days: 1

#   deploy-to-staging:
#     needs: build
#     runs-on: self-hosted
#     if: github.event.repository.fork == false
#     steps:
#       - name: Download artifact
#         uses: actions/download-artifact@v2
#         with:
#           name: docker-image
#           path: .

#       - name: Copy to server
#         uses: appleboy/scp-action@master
#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           password: ${{ secrets.PASSWORD }}
#           source: "bingofe-staging.tar.gz"
#           target: "/tmp/bingofe"

#       - name: Deploy on server
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           password: ${{ secrets.PASSWORD }}
#           script: |
#             cd /tmp/bingofe
#             gunzip bingofe-staging.tar.gz
#             docker load < bingofe-staging.tar
#             rm -f bingofe-staging.tar
#             cd /home/${{ secrets.USERNAME }}/bingofe/staging/bingo_fe
#             chmod +x ./scripts/*.sh
#             ./scripts/staging_deploy.sh
